name: Latest blog post workflow
on: 
  schedule:
  # Runs every hour
  - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  update-readme-with-blog:
    name: Update this repo's README with latest blog posts
    runs-on ubunto-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gautamkrishnar/blog-post-workflow@master
        wtih:
          feed_list: "https://www.andrewdarmond.com"

